"""add deleted_at columns to entiti base"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b50940838257'
down_revision: Union[str, None] = '61b3669d4a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'is_system')
    op.drop_column('refresh_tokens', 'deleted_at')
    op.drop_column('products', 'deleted_at')
    op.drop_column('categories', 'deleted_at')
    # ### end Alembic commands ###
