from typing import Optional, Protocol

from fastapi_pagination import Page, Params

from app.models.category import Category
from app.models.permission import Permission
from app.models.product import Product
from app.models.refresh_token import RefreshToken
from app.models.role import Role
from app.models.user import User


class CategoryRepositoryPort(Protocol):
    def list(self, params: Params, sort: list[str] | None, search: str | None) -> Page[Category]: ...
    def get(self, category_id: int) -> Optional[Category]: ...
    def get_by_name(self, name: str) -> Optional[Category]: ...
    def add(self, category: Category) -> Category: ...
    def save(self, category: Category) -> Category: ...
    def delete(self, category: Category) -> None: ...
    def restore(self, category_id: int) -> Optional[Category]: ...


class ProductRepositoryPort(Protocol):
    def list(self, params: Params, sort: list[str] | None, search: str | None) -> Page[Product]: ...
    def get(self, product_id: int) -> Optional[Product]: ...
    def add(self, product: Product) -> Product: ...
    def save(self, product: Product) -> Product: ...
    def delete(self, product: Product) -> None: ...
    def restore(self, product_id: int) -> Optional[Product]: ...


class UserRepositoryProtocol(Protocol):
    def get_by_id(
        self, user_id: int, with_role: bool = False, with_permissions: bool = False
    ) -> Optional[User]: ...
    def get_by_username(
        self, username: str, with_role: bool = False, with_permissions: bool = False
    ) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def exists_with_role(self, role_id: int, exclude_user_id: Optional[int] = None) -> bool: ...
    def list(
        self,
        params: Params,
        sort: list[str] | None,
        search: str | None,
        with_role: bool = False,
    ) -> Page[User]: ...
    def create(self, user: User) -> User: ...
    def save(self, user: User) -> User: ...
    def delete(self, user: User) -> None: ...
    def restore(self, user_id: int) -> Optional[User]: ...


class RoleRepositoryProtocol(Protocol):
    def get_by_id(self, role_id: int, with_permissions: bool = False) -> Optional[Role]: ...
    def get_by_name(self, name: str, with_permissions: bool = False) -> Optional[Role]: ...
    def list_all(self, with_permissions: bool = False) -> list[Role]: ...
    def create(self, role: Role) -> Role: ...
    def save(self, role: Role) -> Role: ...
    def delete(self, role: Role) -> None: ...
    def restore(self, role_id: int) -> Optional[Role]: ...


class PermissionRepositoryProtocol(Protocol):
    def get_by_id(self, permission_id: int) -> Optional[Permission]: ...
    def get_by_name(self, name: str) -> Optional[Permission]: ...
    def get_by_ids(self, ids: list[int]) -> list[Permission]: ...
    def get_or_create(self, name: str, title: str | None = None) -> Permission: ...
    def list_all(self) -> list[Permission]: ...
    def save(self, permission: Permission) -> Permission: ...


class RefreshTokenRepositoryProtocol(Protocol):
    def create(self, refresh_token: RefreshToken) -> RefreshToken: ...
    def get_by_token_hash(
        self, token_hash: str, with_user_permissions: bool = False
    ) -> Optional[RefreshToken]: ...
    def save(self, refresh_token: RefreshToken) -> RefreshToken: ...
    def revoke_family(self, family_id: str) -> None: ...
    def commit(self) -> None: ...
