from typing import Protocol


class PasswordHasherPort(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hashed: str) -> bool: ...


class AccessTokenPort(Protocol):
    def create(self, user_id: int) -> str: ...
    def decode(self, token: str) -> int: ...


class OpaqueTokenPort(Protocol):
    def generate(self) -> str: ...
    def hash(self, raw_token: str) -> str: ...
