from typing import Protocol

from fastapi_pagination import Page, Params

from app.models.category import Category
from app.models.product import Product


class CategoryRepositoryPort(Protocol):
    def list(self, params: Params, sort: list[str] | None, search: str | None) -> Page[Category]: ...
    def get(self, category_id: int) -> Category | None: ...
    def add(self, category: Category) -> Category: ...
    def save(self, category: Category) -> Category: ...
    def delete(self, category: Category) -> None: ...


class ProductRepositoryPort(Protocol):
    def list(self, params: Params, sort: list[str] | None, search: str | None) -> Page[Product]: ...
    def get(self, product_id: int) -> Product | None: ...
    def add(self, product: Product) -> Product: ...
    def save(self, product: Product) -> Product: ...
    def delete(self, product: Product) -> None: ...